[workspace]
members = [
    "crates/wasi_nn_burnrs",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.4.0"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/WasmEdge/rust-plugins"
homepage = "https://github.com/WasmEdge/rust-plugins"
